# Dependencies

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp
from matplotlib.gridspec import GridSpec

# local dependencies
from utilities.dft import (
    fourier_basis_1d,
    fourier_basis_2d,
    dft,
    idft,
    dft2,
    idft2
)

from utilities.filters import (
    ideal as ideal_filter,
    sinc as sinc_filter,
    gaussian as gaussian_filter
)

# Discrete Fourier Transform (DFT)

## 1-dimensional signal

In [ ]:
# create basis vectors with period(N) = 5
signal_1d_length = 5
basis_vectors = fourier_basis_1d(signal_1d_length)

# plot
fig, axs = plt.subplots(nrows=3, ncols=signal_1d_length, figsize=(16, 4), layout='compressed')
fig.suptitle("1D DFT basis vectors")

for i in range(signal_1d_length):
    axs[0, i].imshow(basis_vectors[i, :].real.reshape(1, -1), cmap='gray', vmin=basis_vectors.real.min(), vmax=basis_vectors.real.max())
    axs[0, i].set_title(f"basis: {i} [real]")
    axs[0, i].set_yticks([])
    axs[0, i].set_xticks(range(signal_1d_length))
    axs[1, i].imshow(basis_vectors[i, :].imag.reshape(1, -1), cmap='gray', vmin=basis_vectors.imag.min(), vmax=basis_vectors.imag.max())
    axs[1, i].set_title(f"basis: {i} [imaginary]")
    axs[1, i].set_yticks([])
    axs[1, i].set_xticks(range(signal_1d_length))
    axs[2, i].imshow(np.abs(basis_vectors[i, :]).reshape(1, -1), cmap='gray', vmin=np.abs(basis_vectors).min(), vmax=np.abs(basis_vectors).max())
    axs[2, i].set_title(f"basis: {i} [magnitude]")
    axs[2, i].set_yticks([])
    axs[2, i].set_xticks(range(signal_1d_length))

plt.show()

In [5]:
print(f"real part of basis vectors:\n{basis_vectors.real}")

real part of basis vectors:
[[ 1.          1.          1.          1.          1.        ]
 [ 1.          0.30901699 -0.80901699 -0.80901699  0.30901699]
 [ 1.         -0.80901699  0.30901699  0.30901699 -0.80901699]
 [ 1.         -0.80901699  0.30901699  0.30901699 -0.80901699]
 [ 1.          0.30901699 -0.80901699 -0.80901699  0.30901699]]


In [6]:
print(f"imaginary part of basis vectors:\n{basis_vectors.imag}")

imaginary part of basis vectors:
[[ 0.          0.          0.          0.          0.        ]
 [ 0.         -0.95105652 -0.58778525  0.58778525  0.95105652]
 [ 0.         -0.58778525  0.95105652 -0.95105652  0.58778525]
 [ 0.          0.58778525 -0.95105652  0.95105652 -0.58778525]
 [ 0.          0.95105652  0.58778525 -0.58778525 -0.95105652]]


## 2-dimensional signal

In [7]:
# create basis images with period(N, N) = (8, 8)
signal_2d_length = 8
basis_images = fourier_basis_2d(signal_2d_length)

In [ ]:
# plot
fig, axs = plt.subplots(nrows=signal_2d_length, ncols=signal_2d_length, figsize=(16, 18), layout='compressed')
fig.suptitle("2D DFT basis images [real part]")

for i in range(signal_2d_length):
    for j in range(signal_2d_length):
        axs[i, j].imshow(basis_images[i, j].real.reshape(signal_2d_length, signal_2d_length), cmap='gray', vmin=basis_images.real.min(), vmax=basis_images.real.max())
        axs[i, j].set_title(f"basis: {i},{j}")
        axs[i, j].set_yticks([])
        axs[i, j].set_xticks([])

plt.show()

In [ ]:
# plot
fig, axs = plt.subplots(nrows=signal_2d_length, ncols=signal_2d_length, figsize=(16, 18), layout='compressed')
fig.suptitle("1d basis vectors [imaginary part]")

for i in range(signal_2d_length):
    for j in range(signal_2d_length):
        axs[i, j].imshow(basis_images[i, j].imag.reshape(signal_2d_length, signal_2d_length), cmap='gray', vmin=basis_images.imag.min(), vmax=basis_images.imag.max())
        axs[i, j].set_title(f"basis: {i},{j}")
        axs[i, j].set_yticks([])
        axs[i, j].set_xticks([])

plt.show()

## Reconstructing a 1d signal

In [ ]:
# 1d array of length 5 (N=5 which is considered as the period of the signal)
arr1 = np.array([3, 0, 2, 1, 5])

# DFT : transform signal from spatial domain to frequency domain
dft_arr1 = dft(arr1)

# IDFT: transform signal from frequency domain to spatial domain
idft_arr1 = idft(dft_arr1)

# take only the real part because our original signal is a real part
idft_arr1 = idft_arr1.real

# clip the signal values in range(0, 5) [in this case we know that for example our original signal must have values in this range]
idft_arr1 = idft_arr1.clip(arr1.min(), arr1.max())

# change dtype from float to int (original signal had integer values)
idft_arr1 = np.round(idft_arr1).astype(np.int32)

# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(12, 2), layout='compressed')
fig.suptitle("Reconstructing 1D signal")

axs[0].imshow(arr1.reshape(1, -1), cmap='gray')
axs[0].set_title("Original signal")
axs[1].imshow(np.abs(dft_arr1).reshape(1, -1), cmap='gray')
axs[1].set_title("Magnitude in frequency domain")
axs[2].imshow(idft_arr1.reshape(1, -1), cmap='gray')
axs[2].set_title("Reconstructed signal")

for ax in fig.axes:
    ax.set_yticks([])

plt.show()

## Reconstructing a 2d signal

In [ ]:
# 2d array of length 3x3
arr2 = np.array([[1, 1, 3], [2, 1, 2], [2, 3, 3]])

# DFT : transform signal from spatial domain to frequency domain
dft_arr2 = dft2(arr2)

# IDFT: transform signal from frequency domain to spatial domain
idft_arr2 = idft2(dft_arr2)

# take only the real part because our original signal is a real part
idft_arr2 = idft_arr2.real

# clip the signal values in range(1, 3) [in this case we know that for example our original signal must have values in this range]
idft_arr2 = idft_arr2.clip(arr2.min(), arr2.max())

# change dtype from float to int (original signal had integer values)
idft_arr2 = np.round(idft_arr2).astype(np.int32)

# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(12, 5), layout='compressed')
fig.suptitle("Reconstructing 2D signal")

axs[0].imshow(arr2, cmap='gray')
axs[0].set_title("Original signal")
axs[1].imshow(np.abs(dft_arr2), cmap='gray')
axs[1].set_title("Magnitude in frequency domain")
axs[2].imshow(idft_arr2, cmap='gray')
axs[2].set_title("Reconstructed signal")

for ax in fig.axes:
    ax.set_xticks(range(3))
    ax.set_yticks(range(3))

plt.show()

# Discrete Fourier Transform Using numpy
   - Discrete Fourier Transform (DFT) is calculated using the efficient Fast Fourier Transform (FFT) algorithm.

## f(x) = 1
   - DFT(f(x)) = impulse signal

In [12]:
# ideal signal
signal_length = 200
signal = np.ones(shape=(signal_length,))

# fft
fft_signal = np.fft.fft(signal)

# shift the low frequencies to the center
fftshift_signal = np.fft.fftshift(fft_signal)

# magnitude of the signal
mag_fft_signal = np.abs(fft_signal)
mag_fftshift_signal = np.abs(fftshift_signal)

# phase of the signal
phase_fft_signal = np.angle(fft_signal)
phase_fftshift_signal = np.angle(fftshift_signal)

# reconstruct the signal
reconstructed_signal = np.fft.ifft(np.fft.ifftshift(fftshift_signal)).real

In [ ]:
# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 4), layout='compressed')

axs[0].plot(signal)
axs[0].set_title('Original signal')
axs[1].plot(fftshift_signal.real)
axs[1].set_title('fft [real]')
axs[2].plot(fftshift_signal.imag)
axs[2].set_title('fft [imaginary]')

plt.show()

## Square 1D Signal

In [14]:
# ideal signal
signal_length = 200
ideal_signal = np.zeros(shape=(signal_length,))
ideal_signal[:signal_length // 10] = 1

# fft
fft_ideal_signal = np.fft.fft(ideal_signal)

# shift the low frequencies to the center
fftshift_ideal_signal = np.fft.fftshift(fft_ideal_signal)

# magnitude of the signal
mag_fft_ideal_signal = np.abs(fft_ideal_signal)
mag_fftshift_ideal_signal = np.abs(fftshift_ideal_signal)

# phase of the signal
phase_fft_ideal_signal = np.angle(fft_ideal_signal)
phase_fftshift_ideal_signal = np.angle(fftshift_ideal_signal)

# reconstruct the signal
reconstructed_ideal_signal = np.fft.ifft(np.fft.ifftshift(fftshift_ideal_signal)).real

In [ ]:
# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 4), layout='compressed')

axs[0].plot(ideal_signal)
axs[0].set_title('Original signal')
axs[1].plot(fftshift_ideal_signal.real)
axs[1].set_title('fft [real]')
axs[2].plot(fftshift_ideal_signal.imag)
axs[2].set_title('fft [imaginary]')

plt.show()

In [ ]:
# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 4), layout='compressed')

axs[0].plot(ideal_signal)
axs[0].set_title('Original signal')
axs[1].plot(mag_fft_ideal_signal)
axs[1].set_title('Magnitude')
axs[2].plot(mag_fftshift_ideal_signal)
axs[2].set_title('Magnitude [fftshift]')

plt.show()

In [ ]:
# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 4), layout='compressed')

axs[0].plot(ideal_signal)
axs[0].set_title('Original signal')
axs[1].plot(mag_fftshift_ideal_signal)
axs[1].set_title('Magnitude [shifted version]')
axs[2].plot(phase_fftshift_ideal_signal)
axs[2].set_title('Phase [shifted version]')

plt.show()

In [ ]:
# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 4), layout='compressed')

axs[0].plot(ideal_signal)
axs[0].set_title('Original signal')
axs[1].plot(mag_fftshift_ideal_signal)
axs[1].set_title('Magnitude [shifted version]')
axs[2].plot(reconstructed_ideal_signal)
axs[2].set_title('Reconstructed signal')

plt.show()

In [19]:
# sinc signal
signal_length = 200
t = np.linspace(-20, 20, signal_length)
sinc_signal = np.sinc(t)

# fft
fft_sinc_signal = np.fft.fft(sinc_signal)

# shift the low frequencies to the center
fftshift_sinc_signal = np.fft.fftshift(fft_sinc_signal)

# magnitude of the signal
mag_fftshift_sinc_signal = np.abs(fftshift_sinc_signal)

# phase of the signal
phase_fftshift_sinc_signal = np.angle(fftshift_sinc_signal)

# reconstruct the signal
reconstructed_sinc_signal = np.fft.ifft(fft_sinc_signal).real

In [ ]:
# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 4), layout='compressed')

axs[0].plot(sinc_signal)
axs[0].set_title('Original signal')
axs[1].plot(mag_fftshift_sinc_signal)
axs[1].set_title('Magnitude [shifted version]')
axs[2].plot(reconstructed_sinc_signal)
axs[2].set_title('Reconstructed signal')

plt.show()

## 2D Block signal

In [ ]:
# create a 2d square ideal low-pass filter
image_size = (256, 256)
block_size = 8
block_2d = ideal_filter(image_size, block_size, shape='square')

# apply 2d fast-fourier transform
fft_block_2d = np.fft.fft2(block_2d)
fftshift_block_2d = np.fft.fftshift(fft_block_2d)

# magnitude & phase
abs_fft_block_2d = np.abs(fft_block_2d)
phase_fft_block_2d = np.angle(fft_block_2d)

# magnitude & phase [shifted version]
abs_fftshift_block_2d = np.abs(fftshift_block_2d)
phase_fftshift_block_2d = np.angle(fftshift_block_2d)

# reconstruct the image
ifft_block_2d = np.fft.ifft2(fft_block_2d).real.clip(0, 1)

# plot
fig, axs = plt.subplots(nrows=2, ncols=3, figsize=(12, 6), layout='compressed')

axs[0, 0].imshow(block_2d, cmap='gray')
axs[0, 0].set_title("Original image")
axs[0, 0].axis('off')
axs[0, 1].imshow(np.log2(abs_fft_block_2d + 1), cmap='gray')
axs[0, 1].set_title("log2(magnitude)")
axs[0, 1].axis('off')
axs[0, 2].imshow(phase_fft_block_2d, cmap='gray')
axs[0, 2].set_title("phase")
axs[0, 2].axis('off')
axs[1, 0].imshow(ifft_block_2d, cmap='gray')
axs[1, 0].set_title("Reconstructed image")
axs[1, 0].axis('off')
axs[1, 1].imshow(np.log2(abs_fftshift_block_2d + 1), cmap='gray')
axs[1, 1].set_title("log2(magnitude) [shift]")
axs[1, 1].axis('off')
axs[1, 2].imshow(phase_fftshift_block_2d, cmap='gray')
axs[1, 2].set_title("phase [shift]")
axs[1, 2].axis('off')

plt.show()

## Ideal low-pass & cardinal sine (sinc) filters

In [22]:
# create a 2d circular ideal low-pass filter
image_size = (256, 256)
cutoff_frequency = 16
ilpf = ideal_filter(image_size, cutoff_frequency)

# apply 2d fast-fourier transform
fft_ilpf = np.fft.fft2(ilpf)
fftshift_ilpf = np.fft.fftshift(fft_ilpf)

# magnitude & phase
abs_fft_ilpf = np.abs(fft_ilpf)
phase_fft_ilpf = np.angle(fft_ilpf)

# magnitude & phase [shifted version]
abs_fftshift_ilpf = np.abs(fftshift_ilpf)
phase_fftshift_ilpf = np.angle(fftshift_ilpf)

# reconstruct the image
ifft_ilpf = np.fft.ifft2(fft_ilpf).real.clip(0, 1)

In [ ]:
# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(12, 3), layout='compressed')

axs[0].imshow(ilpf, cmap='gray')
axs[0].set_title("Original image")
axs[0].axis('off')
axs[1].imshow(np.abs(fftshift_ilpf.real), cmap='gray')
axs[1].set_title("fft [real]")
axs[1].axis('off')
axs[2].imshow(np.abs(fftshift_ilpf.imag), cmap='gray')
axs[2].set_title("fft [imaginary]")
axs[2].axis('off')

plt.show()

In [ ]:
# plot
fig, axs = plt.subplots(nrows=2, ncols=3, figsize=(12, 6), layout='compressed')

axs[0, 0].imshow(ilpf, cmap='gray')
axs[0, 0].set_title("Original image")
axs[0, 0].axis('off')
axs[0, 1].imshow(np.log2(abs_fft_ilpf + 1), cmap='gray')
axs[0, 1].set_title("log2(magnitude)")
axs[0, 1].axis('off')
axs[0, 2].imshow(phase_fft_ilpf, cmap='gray')
axs[0, 2].set_title("phase")
axs[0, 2].axis('off')
axs[1, 0].imshow(ifft_ilpf, cmap='gray')
axs[1, 0].set_title("Reconstructed image")
axs[1, 0].axis('off')
axs[1, 1].imshow(np.log2(abs_fftshift_ilpf + 1), cmap='gray')
axs[1, 1].set_title("log2(magnitude) [shifted version]")
axs[1, 1].axis('off')
axs[1, 2].imshow(phase_fftshift_ilpf, cmap='gray')
axs[1, 2].set_title("phase [shifted version]")
axs[1, 2].axis('off')

plt.show()

In [ ]:
# create a 2d sinc filter
image_size = (256, 256)
sigma = 2
sinc = sinc_filter(image_size, sigma)

# apply 2d fast-fourier transform
fft_sinc = np.fft.fft2(sinc)
fftshift_sinc = np.fft.fftshift(fft_sinc)

# magnitude & phase [shifted version]
abs_fftshift_sinc = np.abs(fftshift_sinc)
phase_fftshift_sinc = np.angle(fftshift_sinc)

# reconstruct the image
ifft_sinc = np.fft.ifft2(fft_sinc).real.clip(0, 1)

# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(12, 3), layout='compressed')

axs[0].imshow(sinc, cmap='gray')
axs[0].set_title("Original image")
axs[0].axis('off')
axs[1].imshow(np.log2(abs_fftshift_sinc + 1), cmap='gray')
axs[1].set_title("magnitude [shifted version]")
axs[1].axis('off')
axs[2].imshow(ifft_sinc, cmap='gray')
axs[2].set_title("Reconstructed image")
axs[2].axis('off')

plt.show()

## Signal shifting effect on magnitude & phase

In [ ]:
# create two separaet vertical lines
image_size = 256
vertical_1 = np.zeros(shape=(image_size, image_size))
vertical_1[:, int(1.5 * image_size // 4): int(2.5 * image_size // 4)] = 1

vertical_2 = np.zeros(shape=(image_size, image_size))
vertical_2[:, int(.5 * image_size // 4): int(1.5 * image_size // 4)] = 1

# fft2
fftshift_vertical_1 = np.fft.fftshift(np.fft.fft2(vertical_1))
fftshift_vertical_2 = np.fft.fftshift(np.fft.fft2(vertical_2))

# magnitude
abs_fftshift_vertical_1 = np.abs(fftshift_vertical_1)
abs_fftshift_vertical_2 = np.abs(fftshift_vertical_2)

# phase
phase_fftshift_vertical_1 = np.angle(fftshift_vertical_1)
phase_fftshift_vertical_2 = np.angle(fftshift_vertical_2)

# plot
fig, axs = plt.subplots(nrows=2, ncols=3, figsize=(12, 6), layout='compressed')

axs[0, 0].imshow(vertical_1, cmap='gray')
axs[0, 0].axis('off')
axs[0, 0].set_title("vertical_1")
axs[0, 1].imshow(np.log2(abs_fftshift_vertical_1 + 1), cmap='gray')
axs[0, 1].axis('off')
axs[0, 1].set_title("Magnitude_1")
axs[0, 2].imshow(phase_fftshift_vertical_1, cmap='gray')
axs[0, 2].axis('off')
axs[0, 2].set_title("Phase_1")
axs[1, 0].imshow(vertical_2, cmap='gray')
axs[1, 0].axis('off')
axs[1, 0].set_title("vertical_2")
axs[1, 1].imshow(np.log2(abs_fftshift_vertical_2 + 1), cmap='gray')
axs[1, 1].axis('off')
axs[1, 1].set_title("Magnitude_2")
axs[1, 2].imshow(phase_fftshift_vertical_2, cmap='gray')
axs[1, 2].axis('off')
axs[1, 2].set_title("Phase_2")

plt.show()

In [ ]:
# create two separate horizontal lines
image_size = 256
horizontal_1 = np.zeros(shape=(image_size, image_size))
horizontal_1[int(1.5 * image_size // 4): int(2.5 * image_size // 4), :] = 1

horizontal_2 = np.zeros(shape=(image_size, image_size))
horizontal_2[int(.5 * image_size // 4): int(1.5 * image_size // 4), :] = 1

# fft2
fftshift_horizontal_1 = np.fft.fftshift(np.fft.fft2(horizontal_1))
fftshift_horizontal_2 = np.fft.fftshift(np.fft.fft2(horizontal_2))

# magnitude
abs_fftshift_horizontal_1 = np.abs(fftshift_horizontal_1)
abs_fftshift_horizontal_2 = np.abs(fftshift_horizontal_2)

# phase
phase_fftshift_horizontal_1 = np.angle(fftshift_horizontal_1)
phase_fftshift_horizontal_2 = np.angle(fftshift_horizontal_2)

# plot
fig, axs = plt.subplots(nrows=2, ncols=3, figsize=(12, 6), layout='compressed')

axs[0, 0].imshow(horizontal_1, cmap='gray')
axs[0, 0].axis('off')
axs[0, 0].set_title("horizontal_1")
axs[0, 1].imshow(np.log2(abs_fftshift_horizontal_1 + 1), cmap='gray')
axs[0, 1].axis('off')
axs[0, 1].set_title("Magnitude_1")
axs[0, 2].imshow(phase_fftshift_horizontal_1, cmap='gray')
axs[0, 2].axis('off')
axs[0, 2].set_title("Phase_1")
axs[1, 0].imshow(horizontal_2, cmap='gray')
axs[1, 0].axis('off')
axs[1, 0].set_title("horizontal_2")
axs[1, 1].imshow(np.log2(abs_fftshift_horizontal_2 + 1), cmap='gray')
axs[1, 1].axis('off')
axs[1, 1].set_title("Magnitude_2")
axs[1, 2].imshow(phase_fftshift_horizontal_2, cmap='gray')
axs[1, 2].axis('off')
axs[1, 2].set_title("Phase_2")

plt.show()

## Signal rotation effect on magnitude & phase

In [ ]:
# load lenna.jpg
lenna_1 = plt.imread('../assets/images/lenna.jpg')
lenna_2 = np.rot90(lenna_1)

# fft2
fftshift_lenna_1 = np.fft.fftshift(np.fft.fft2(lenna_1))
fftshift_lenna_2 = np.fft.fftshift(np.fft.fft2(lenna_2))

# magnitude
abs_fftshift_lenna_1 = np.abs(fftshift_lenna_1)
abs_fftshift_lenna_2 = np.abs(fftshift_lenna_2)

# phase
phase_fftshift_lenna_1 = np.angle(fftshift_lenna_1)
phase_fftshift_lenna_2 = np.angle(fftshift_lenna_2)

# plot
fig, axs = plt.subplots(nrows=2, ncols=3, figsize=(12, 6), layout='compressed')

axs[0, 0].imshow(lenna_1, cmap='gray')
axs[0, 0].axis('off')
axs[0, 0].set_title("lenna_1")
axs[0, 1].imshow(np.log2(abs_fftshift_lenna_1 + 1), cmap='gray')
axs[0, 1].axis('off')
axs[0, 1].set_title("magnitude_1")
axs[0, 2].imshow(phase_fftshift_lenna_1, cmap='gray')
axs[0, 2].axis('off')
axs[0, 2].set_title("phase_1")
axs[1, 0].imshow(lenna_2, cmap='gray')
axs[1, 0].axis('off')
axs[1, 0].set_title("lenna_2")
axs[1, 1].imshow(np.log2(abs_fftshift_lenna_2 + 1), cmap='gray')
axs[1, 1].axis('off')
axs[1, 1].set_title("magnitude_2")
axs[1, 2].imshow(phase_fftshift_lenna_2, cmap='gray')
axs[1, 2].axis('off')
axs[1, 2].set_title("phase_2")

plt.show()

## Signal flip effect on magnitude & phase

In [ ]:
# load lenna.jpg
cm_1 = plt.imread("../assets/images/CH02_Fig0222(b)(cameraman).tif")
cm_2 = np.fliplr(cm_1)

# fft2
fftshift_cm_1 = np.fft.fftshift(np.fft.fft2(cm_1))
fftshift_cm_2 = np.fft.fftshift(np.fft.fft2(cm_2))

# magnitude
abs_fftshift_cm_1 = np.abs(fftshift_cm_1)
abs_fftshift_cm_2 = np.abs(fftshift_cm_2)

# phase
phase_fftshift_cm_1 = np.angle(fftshift_cm_1)
phase_fftshift_cm_2 = np.angle(fftshift_cm_2)

# plot
fig, axs = plt.subplots(nrows=2, ncols=3, figsize=(12, 6), layout='compressed')

axs[0, 0].imshow(cm_1, cmap='gray')
axs[0, 0].axis('off')
axs[0, 0].set_title("cameraman_1")
axs[0, 1].imshow(np.log2(abs_fftshift_cm_1 + 1), cmap='gray')
axs[0, 1].axis('off')
axs[0, 1].set_title("magnitude_1")
axs[0, 2].imshow(phase_fftshift_cm_1, cmap='gray')
axs[0, 2].axis('off')
axs[0, 2].set_title("phase_1")
axs[1, 0].imshow(cm_2, cmap='gray')
axs[1, 0].axis('off')
axs[1, 0].set_title("cameraman_2")
axs[1, 1].imshow(np.log2(abs_fftshift_cm_2 + 1), cmap='gray')
axs[1, 1].axis('off')
axs[1, 1].set_title("magnitude_2")
axs[1, 2].imshow(phase_fftshift_cm_2, cmap='gray')
axs[1, 2].axis('off')
axs[1, 2].set_title("phase_2")

plt.show()

## Energy equality of a signal in spatial & frequency domain

In [ ]:
# load lenna.jpg
lenna = plt.imread('../assets/images/lenna.jpg')

# fft2
fft_lenna = np.fft.fft2(lenna, norm='ortho')
fftshift_lenna = np.fft.fftshift(fft_lenna)

# reconstructed lenna
reconstructed_lenna = np.fft.ifft2(fft_lenna, norm='ortho').real.clip(0, 255).astype(np.uint8)

# enery calculation
energy_1 = np.sum(np.abs(lenna.astype(np.float64))**2)
energy_2 = np.sum(np.abs(fft_lenna) ** 2)
energy_3 = np.sum(np.abs(reconstructed_lenna.astype(np.float64)) ** 2)

# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(12, 3), layout='compressed')

axs[0].imshow(lenna, cmap='gray')
axs[0].axis('off')
axs[0].set_title(f"original [E= {round(energy_1)}]")
axs[1].imshow(np.log2(np.abs(fftshift_lenna) + 1), cmap='gray')
axs[1].axis('off')
axs[1].set_title(f"frequency [E= {round(energy_2)}]")
axs[2].imshow(reconstructed_lenna, cmap='gray')
axs[2].axis('off')
axs[2].set_title(f"reconstructed [E= {round(energy_3)}]")

plt.show()

## Reconstruct from only magnitude / phase

In [ ]:
# load lenna.jpg
lenna = plt.imread('../assets/images/lenna.jpg')

# fft2
fftshift_lenna = np.fft.fftshift(np.fft.fft2(lenna))
abs_fftshift_lenna = np.abs(fftshift_lenna)
phase_fftshift_lenna = np.angle(fftshift_lenna)

# reconstructed lenna [only magnitude]
reconstructed_abs_lenna = np.fft.ifft2(np.fft.ifftshift(abs_fftshift_lenna)).real.clip(0, 255).astype(np.uint8)

# reconstructed lenna [only phase]
reconstructed_phase_lenna = np.fft.ifft2(np.fft.ifftshift(np.exp(1j * phase_fftshift_lenna))).real

# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 6), layout='compressed')

axs[0].imshow(lenna, cmap='gray')
axs[0].axis('off')
axs[0].set_title(f"original")
axs[1].imshow(reconstructed_abs_lenna, cmap='gray')
axs[1].axis('off')
axs[1].set_title(f"reconstructed [only magnitude]")
axs[2].imshow(reconstructed_phase_lenna, cmap='gray')
axs[2].axis('off')
axs[2].set_title(f"reconstructed [only phase]")

plt.show()

## Ringing effect when using ideal filters

In [ ]:
# load cameraman.tif
cm = plt.imread('../assets/images/CH02_Fig0222(b)(cameraman).tif')

# create several ideal low-pass filters
ilpf_1 = ideal_filter(cm.shape, 32)
ilpf_2 = ideal_filter(cm.shape, 16)
ilpf_3 = ideal_filter(cm.shape, 8)

# fft2
fft_cm = np.fft.fftshift(np.fft.fft2(cm))

# applying filters
cm_ilpf_1 = fft_cm * ilpf_1
cm_ilpf_2 = fft_cm * ilpf_2
cm_ilpf_3 = fft_cm * ilpf_3

# reconstruct cm
ifft_cm_ilpf_1 = np.fft.ifft2(np.fft.ifftshift(cm_ilpf_1)).real.clip(0, 255).astype(np.uint8)
ifft_cm_ilpf_2 = np.fft.ifft2(np.fft.ifftshift(cm_ilpf_2)).real.clip(0, 255).astype(np.uint8)
ifft_cm_ilpf_3 = np.fft.ifft2(np.fft.ifftshift(cm_ilpf_3)).real.clip(0, 255).astype(np.uint8)

# plot
fig, axs = plt.subplots(nrows=4, ncols=3, figsize=(12, 16), layout='compressed')

axs[0, 0].imshow(ilpf_1, cmap='gray')
axs[0, 0].axis('off')
axs[0, 0].set_title("ilpf_1")
axs[0, 1].imshow(ilpf_2, cmap='gray')
axs[0, 1].axis('off')
axs[0, 1].set_title("ilpf_2")
axs[0, 2].imshow(ilpf_3, cmap='gray')
axs[0, 2].axis('off')
axs[0, 2].set_title("ilpf_3")
axs[1, 0].imshow(np.log2(np.abs(cm_ilpf_1) + 1), cmap='gray')
axs[1, 0].axis('off')
axs[1, 0].set_title("Magnitude 1")
axs[1, 1].imshow(np.log2(np.abs(cm_ilpf_2) + 1), cmap='gray')
axs[1, 1].axis('off')
axs[1, 1].set_title("Magnitude 2")
axs[1, 2].imshow(np.log2(np.abs(cm_ilpf_3) + 1), cmap='gray')
axs[1, 2].axis('off')
axs[1, 2].set_title("Magnitude 3")
axs[2, 0].imshow(np.angle(cm_ilpf_1), cmap='gray')
axs[2, 0].axis('off')
axs[2, 0].set_title("Phase 1")
axs[2, 1].imshow(np.angle(cm_ilpf_2), cmap='gray')
axs[2, 1].axis('off')
axs[2, 1].set_title("Phase 2")
axs[2, 2].imshow(np.angle(cm_ilpf_3), cmap='gray')
axs[2, 2].axis('off')
axs[2, 2].set_title("Phase 3")
axs[3, 0].imshow(ifft_cm_ilpf_1, cmap='gray')
axs[3, 0].axis('off')
axs[3, 0].set_title("Reconstruction 1")
axs[3, 1].imshow(ifft_cm_ilpf_2, cmap='gray')
axs[3, 1].axis('off')
axs[3, 1].set_title("Reconstruction 2")
axs[3, 2].imshow(ifft_cm_ilpf_3, cmap='gray')
axs[3, 2].axis('off')
axs[3, 2].set_title("Reconstruction 3")

plt.show()

In [ ]:
# load cameraman.tif
cm = plt.imread('../assets/images/CH02_Fig0222(b)(cameraman).tif')

# create several Gaussian low-pass filters
glpf_1 = gaussian_filter(cm.shape, 32)
glpf_2 = gaussian_filter(cm.shape, 16)
glpf_3 = gaussian_filter(cm.shape, 8)

# fft2
fft_cm = np.fft.fftshift(np.fft.fft2(cm))

# applying filters
cm_glpf_1 = fft_cm * glpf_1
cm_glpf_2 = fft_cm * glpf_2
cm_glpf_3 = fft_cm * glpf_3

# reconstruct cm
ifft_cm_glpf_1 = np.fft.ifft2(np.fft.ifftshift(cm_glpf_1)).real.clip(0, 255).astype(np.uint8)
ifft_cm_glpf_2 = np.fft.ifft2(np.fft.ifftshift(cm_glpf_2)).real.clip(0, 255).astype(np.uint8)
ifft_cm_glpf_3 = np.fft.ifft2(np.fft.ifftshift(cm_glpf_3)).real.clip(0, 255).astype(np.uint8)

# plot
fig, axs = plt.subplots(nrows=4, ncols=3, figsize=(12, 16), layout='compressed')

axs[0, 0].imshow(glpf_1, cmap='gray')
axs[0, 0].axis('off')
axs[0, 0].set_title("glpf_1")
axs[0, 1].imshow(glpf_2, cmap='gray')
axs[0, 1].axis('off')
axs[0, 1].set_title("glpf_2")
axs[0, 2].imshow(glpf_3, cmap='gray')
axs[0, 2].axis('off')
axs[0, 2].set_title("glpf_3")
axs[1, 0].imshow(np.log2(np.abs(cm_glpf_1) + 1), cmap='gray')
axs[1, 0].axis('off')
axs[1, 0].set_title("Magnitude 1")
axs[1, 1].imshow(np.log2(np.abs(cm_glpf_2) + 1), cmap='gray')
axs[1, 1].axis('off')
axs[1, 1].set_title("Magnitude 2")
axs[1, 2].imshow(np.log2(np.abs(cm_glpf_3) + 1), cmap='gray')
axs[1, 2].axis('off')
axs[1, 2].set_title("Magnitude 3")
axs[2, 0].imshow(np.angle(cm_glpf_1), cmap='gray')
axs[2, 0].axis('off')
axs[2, 0].set_title("Phase 1")
axs[2, 1].imshow(np.angle(cm_glpf_2), cmap='gray')
axs[2, 1].axis('off')
axs[2, 1].set_title("Phase 2")
axs[2, 2].imshow(np.angle(cm_glpf_3), cmap='gray')
axs[2, 2].axis('off')
axs[2, 2].set_title("Phase 3")
axs[3, 0].imshow(ifft_cm_glpf_1, cmap='gray')
axs[3, 0].axis('off')
axs[3, 0].set_title("Reconstruction 1")
axs[3, 1].imshow(ifft_cm_glpf_2, cmap='gray')
axs[3, 1].axis('off')
axs[3, 1].set_title("Reconstruction 2")
axs[3, 2].imshow(ifft_cm_glpf_3, cmap='gray')
axs[3, 2].axis('off')
axs[3, 2].set_title("Reconstruction 3")

plt.show()

## Image sharpening using gaussian high-pass filter

In [ ]:
# load cameraman.tif
cm = plt.imread('../assets/images/CH02_Fig0222(b)(cameraman).tif')

# create several Gaussian low-pass filters
ghpf_1 = 1 - gaussian_filter(cm.shape, 64)
ghpf_2 = 1 - gaussian_filter(cm.shape, 32)
ghpf_3 = 1 - gaussian_filter(cm.shape, 16)

# fft2
fft_cm = np.fft.fftshift(np.fft.fft2(cm))

# applying filters
cm_ghpf_1 = fft_cm * ghpf_1
cm_ghpf_2 = fft_cm * ghpf_2
cm_ghpf_3 = fft_cm * ghpf_3

# reconstruct cm
ifft_cm_ghpf_1 = np.fft.ifft2(np.fft.ifftshift(cm_ghpf_1)).real.clip(0, 255).astype(np.uint8)
ifft_cm_ghpf_2 = np.fft.ifft2(np.fft.ifftshift(cm_ghpf_2)).real.clip(0, 255).astype(np.uint8)
ifft_cm_ghpf_3 = np.fft.ifft2(np.fft.ifftshift(cm_ghpf_3)).real.clip(0, 255).astype(np.uint8)

# plot
fig, axs = plt.subplots(nrows=2, ncols=3, figsize=(12, 6), layout='compressed')

axs[0, 0].imshow(ghpf_1, cmap='gray')
axs[0, 0].axis('off')
axs[0, 0].set_title("ghpf_1")
axs[0, 1].imshow(ghpf_2, cmap='gray')
axs[0, 1].axis('off')
axs[0, 1].set_title("ghpf_2")
axs[0, 2].imshow(ghpf_3, cmap='gray')
axs[0, 2].axis('off')
axs[0, 2].set_title("ghpf_3")
axs[1, 0].imshow(ifft_cm_ghpf_1, cmap='gray')
axs[1, 0].axis('off')
axs[1, 0].set_title("Reconstruction 1")
axs[1, 1].imshow(ifft_cm_ghpf_2, cmap='gray')
axs[1, 1].axis('off')
axs[1, 1].set_title("Reconstruction 2")
axs[1, 2].imshow(ifft_cm_ghpf_3, cmap='gray')
axs[1, 2].axis('off')
axs[1, 2].set_title("Reconstruction 3")

plt.show()

In [ ]:
# sharpening cameraman
sharp_cm_1 = (cm.astype(np.float32) + ifft_cm_ghpf_1.astype(np.float32)).clip(0, 255).astype(np.uint8)
sharp_cm_2 = (cm.astype(np.float32) + ifft_cm_ghpf_2.astype(np.float32)).clip(0, 255).astype(np.uint8)
sharp_cm_3 = (cm.astype(np.float32) + ifft_cm_ghpf_3.astype(np.float32)).clip(0, 255).astype(np.uint8)

# plot
fig, axs = plt.subplots(nrows=1, ncols=4, figsize=(16, 4), layout='compressed')

axs[0].imshow(cm, cmap='gray')
axs[0].axis('off')
axs[0].set_title("Original")
axs[1].imshow(sharp_cm_1, cmap='gray')
axs[1].axis('off')
axs[1].set_title("Sharpening 1")
axs[2].imshow(sharp_cm_2, cmap='gray')
axs[2].axis('off')
axs[2].set_title("Sharpening 2")
axs[3].imshow(sharp_cm_3, cmap='gray')
axs[3].axis('off')
axs[3].set_title("Sharpening 3")

plt.show()

## Periodic noise removal

In [ ]:
# load cameraman.tif
lenna = plt.imread('../assets/images/lenna.jpg').astype(np.float64)

# add priodic noise to lenna
v, h = np.meshgrid(np.arange(lenna.shape[0]), np.arange(lenna.shape[1]))
v_period = 16
h_period = 32

noisy_lenna = lenna + 20 * np.sin(2 * np.pi / v_period * v) + 50 * np.cos(2 * np.pi / h_period * h)

# fft2
fft_lenna = np.fft.fftshift(np.fft.fft2(noisy_lenna))

# plot
fig = plt.figure(figsize=(12, 8), layout='constrained')

gs = GridSpec(2, 3, figure=fig)
ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[1, 0])
ax3 = fig.add_subplot(gs[:, 1:])

ax1.imshow(lenna, cmap='gray')
ax1.set_title("Original")
ax2.imshow(noisy_lenna, cmap='gray')
ax2.set_title("Periodic noise")
ax3.imshow(np.log2(np.abs(fft_lenna) + 1)[206:306, 206:306], cmap='gray', vmin=0)
ax3.add_artist(plt.Circle((18, 50), 3, color='red', fill=False))
ax3.add_artist(plt.Circle((82, 50), 3, color='red', fill=False))
ax3.add_artist(plt.Circle((50, 34), 3, color='red', fill=False))
ax3.add_artist(plt.Circle((50, 66), 3, color='red', fill=False))
ax3.set_title("Magnitude of noisy image [zoomed in center [206:306, 206:306]]")


for ax in fig.axes:
    ax.axis('off')

plt.show()

In [ ]:
# destroy some frequencies
fft_lenna[256 - 16, 256] = 0
fft_lenna[256 + 16, 256] = 0
fft_lenna[256, 256 - 32] = 0
fft_lenna[256, 256 + 32] = 0

# reconstruct lenna
ifft_lenna = np.fft.ifft2(np.fft.ifftshift(fft_lenna)).real.clip(0, 255).astype(np.uint8)

# plot
fig = plt.figure(figsize=(12, 8), layout='constrained')

gs = GridSpec(2, 3, figure=fig)
ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[1, 0])
ax3 = fig.add_subplot(gs[:, 1:])

ax1.imshow(noisy_lenna, cmap='gray')
ax1.set_title("Noisy lenna")
ax2.imshow(ifft_lenna, cmap='gray')
ax2.set_title("Denoised lenna")
ax3.imshow(np.log2(np.abs(fft_lenna) + 1)[206:306, 206:306], cmap='gray')
ax3.add_artist(plt.Circle((18, 50), 3, color='red', fill=False))
ax3.add_artist(plt.Circle((82, 50), 3, color='red', fill=False))
ax3.add_artist(plt.Circle((50, 34), 3, color='red', fill=False))
ax3.add_artist(plt.Circle((50, 66), 3, color='red', fill=False))
ax3.set_title("Magnitude of noisy image [zoomed in center [206:306, 206:306]]")

for ax in fig.axes:
    ax.axis('off')

plt.show()

## FFT instead of Circular Convolution

In [ ]:
# load cameraman.tif
cm = plt.imread('../assets/images/CH02_Fig0222(b)(cameraman).tif')

# create a gaussian noise
gaussian_noise = np.random.normal(loc=0, scale=10, size=cm.shape)

# apply gaussian noise to the image
noisy_cm = (cm + gaussian_noise).clip(0, 255).astype(np.uint8)

# plot
fig, axs = plt.subplots(nrows=1, ncols=2, figsize=(8, 4), layout='compressed')

axs[0].imshow(cm, cmap='gray')
axs[0].set_title('Original image')
axs[1].imshow(noisy_cm, cmap='gray')
axs[1].set_title('Noisy image')

for ax in fig.axes:
    ax.axis('off')

plt.show()

In [ ]:
# smooth in spatial domain [using convolution]
glpf = gaussian_filter(size=(5, 5), sigma=1, norm=True)

# convolution
denoised_cm_1 = sp.signal.convolve2d(noisy_cm, glpf, mode='same', boundary='fill')

# clip and dtype
denoised_cm_1 = denoised_cm_1.clip(0, 255).astype(np.uint8)

# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 8), layout='compressed')

axs[0].imshow(cm, cmap='gray')
axs[0].set_title('Original image')
axs[1].imshow(noisy_cm, cmap='gray')
axs[1].set_title('Noisy image')
axs[2].imshow(denoised_cm_1, cmap='gray')
axs[2].set_title('Denoised image')

for ax in fig.axes:
    ax.axis('off')

plt.show()

In [ ]:
# smooth in frequency domain [using fft instead of circular convolution]

# image size : MxM, filter size : NxN -> upscale to (M+N-1, M+N-1)
size = (cm.shape[0] + glpf.shape[1] - 1, cm.shape[0] + glpf.shape[1] - 1)

# pad noisy image to size M+N-1
padded_noisy_cm = np.zeros(shape=size)
padded_noisy_cm[:cm.shape[0], :cm.shape[1]] = noisy_cm

# pad filter to size M+N-1
padded_glpf = np.zeros(shape=size)
padded_glpf[:glpf.shape[0], :glpf.shape[1]] = glpf

# plot
fig, axs = plt.subplots(nrows=1, ncols=2, figsize=(8, 4), layout='compressed')

axs[0].imshow(padded_noisy_cm, cmap='gray')
axs[0].set_title('padded noisy image')
axs[1].imshow(padded_glpf, cmap='gray')
axs[1].set_title('padded filter')
axs[1].add_artist(plt.arrow(40, 40, -25, -25, color='red', head_width=10, head_length=10))

for ax in fig.axes:
    ax.axis('off')

plt.show()

In [ ]:
# fft
fft_padded_noisy_cm = np.fft.fftshift(np.fft.fft2(padded_noisy_cm))
abs_fft_padded_noisy_cm = np.abs(fft_padded_noisy_cm)

fft_padded_glpf = np.fft.fftshift(np.fft.fft2(padded_glpf))
abs_fft_padded_glpf = np.abs(fft_padded_glpf)

fft_multiplication = np.multiply(fft_padded_noisy_cm, fft_padded_glpf)
abs_fft_multiplication = np.abs(fft_multiplication)

# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 8), layout='compressed')

axs[0].imshow(np.log2(abs_fft_padded_noisy_cm + 1), cmap='gray')
axs[0].set_title('Magnitude(noisy_cm)')
axs[1].imshow(np.log2(abs_fft_padded_glpf + 1), cmap='gray')
axs[1].set_title('Magnitude(filter)')
axs[2].imshow(np.log2(abs_fft_multiplication + 1), cmap='gray')
axs[2].set_title('Magnitude(noisy_cm * filter)')

for ax in fig.axes:
    ax.axis('off')

plt.show()

In [ ]:
# reconstruction
ifft_noisy_cm = np.fft.ifft2(np.fft.ifftshift(fft_multiplication)).real

# downscale to size: cm.shape
ifft_noisy_cm = ifft_noisy_cm[glpf.shape[0] // 2:cm.shape[0] + glpf.shape[0] // 2, glpf.shape[1] // 2:cm.shape[1] + glpf.shape[1] // 2]

# clip & dtype
denoised_cm_2 = ifft_noisy_cm.clip(0, 255).astype(np.uint8)

# plot
fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(16, 8), layout='compressed')

axs[0].imshow(noisy_cm, cmap='gray')
axs[0].set_title('Noisy image')
axs[1].imshow(denoised_cm_1, cmap='gray')
axs[1].set_title('Denoised [convolution]')
axs[2].imshow(denoised_cm_2, cmap='gray')
axs[2].set_title('Denoised [fft]')

for ax in fig.axes:
    ax.axis('off')

plt.show()